Development
nikita111100/Online-testing pull request #8
Opened 2020-11-26 21:46 UTC by nikita111100

сделал задания #1,#2,#3

2020-11-26 21:51 UTC, nikita111100 commented
Какие файлы могут быть важны из .gitignore?
В следующий раз наверно лучше создам проект в main а потом делать pr из новой ветки, слишком много кода сейчас добавилось.

2020-11-29 12:48 UTC, allikhachev commented
> Какие файлы могут быть важны из .gitignore?
> В следующий раз наверно лучше создам проект в main а потом делать pr из новой ветки, слишком много кода сейчас добавилось.

В .gitignore можно добавлять все что не важно для проекта
- файлы проекта от ide
- файлы, полученные в результате сборки
- файлы, необходимые для локалного запуска

Да, думаю первым комитом можно добавлять типовой .gitignore.

2020-11-29 13:21 UTC, allikhachev requested changes

2020-11-29 13:21 UTC, allikhachev commented on etc/db/tables_online_testing.sql
> +  `test_theme` VARCHAR(255) NULL DEFAULT NULL,
будем ли мы искать тесты по теме? нужен ли индекс?
будет ли у нас список тем?

2020-11-29 13:21 UTC, allikhachev commented on etc/db/tables_online_testing.sql
> +CREATE SCHEMA IF NOT EXISTS `new_schema1` ;
лучше переименовать

2020-11-29 13:21 UTC, allikhachev commented on etc/db/tables_online_testing.sql
> +  `test_name` VARCHAR(255) NULL DEFAULT NULL,
можно просто `name` и `theme`

2020-11-29 13:21 UTC, allikhachev commented on etc/db/tables_online_testing.sql
> +  `test_id` INT NOT NULL,
можжет ли один вопрос принадежать нескольким тестам? если да, то нельзя хранить здесь "ссылку" на тест

2020-11-29 13:21 UTC, allikhachev commented on etc/db/tables_online_testing.sql
> +CREATE TABLE IF NOT EXISTS `new_schema1`.`possible_answer_question` (
можно просто `possible_answer`

2020-11-29 13:21 UTC, allikhachev commented on etc/db/tables_online_testing.sql
> +  `text_answer` VARCHAR(255) NULL DEFAULT NULL,
можно просто `text`

2020-11-29 13:21 UTC, allikhachev commented on etc/db/tables_online_testing.sql
> +CREATE TABLE IF NOT EXISTS `new_schema1`.`questions` (
где ханится номер правильного ответа?

2020-11-29 13:21 UTC, allikhachev commented on etc/db/tables_online_testing.sql
> +  `result` INT NOT NULL,
вычисляемое поле. Можно не хранить

2020-11-29 13:21 UTC, allikhachev commented on etc/db/tables_online_testing.sql
> +  `id_user` INT NULL DEFAULT NULL,
как может быть результат без пользователя?

2020-11-29 13:21 UTC, allikhachev commented on etc/db/tables_online_testing.sql
> +CREATE TABLE IF NOT EXISTS `new_schema1`.`answer_test` (
давай переименуем в `result`

2020-11-29 13:21 UTC, allikhachev commented on etc/db/tables_online_testing.sql
> +CREATE TABLE IF NOT EXISTS `new_schema1`.`answer_question` (
можно просто `answer`

2020-11-29 13:21 UTC, allikhachev commented on etc/db/tables_online_testing.sql
> +  `id_user` INT NULL DEFAULT NULL,
это не нужно

2020-11-29 13:21 UTC, allikhachev commented on etc/db/tables_online_testing.sql
> +  `answer_to_the_question` VARCHAR(255) NOT NULL,
зачем нам это? мы будем позволять вводить текстовые ответы?

2020-11-29 13:21 UTC, allikhachev commented on etc/db/tables_online_testing.sql
> +  `correct_answer` VARCHAR(45) NULL DEFAULT NULL,
зачем нам это?

2020-11-29 13:21 UTC, allikhachev commented on etc/db/tables_online_testing.sql
> +  `questions_id` INT NOT NULL,
это можно удалить

2020-11-29 13:21 UTC, allikhachev commented on etc/db/tables_online_testing.sql
> +CREATE TABLE IF NOT EXISTS `new_schema1`.`user_has_answer_test` (
можем ли мы обойтись без неё?

2020-11-29 13:21 UTC, allikhachev commented on etc/db/tables_online_testing.sql
> +  `test_id` INT NOT NULL,
может здесь хранить ссылку на `user_has_test`?

2020-11-29 13:21 UTC, allikhachev commented on etc/db/tables_online_testing.sql
> +CREATE TABLE IF NOT EXISTS `new_schema1`.`user_has_test` (
давай переименуем в `user_tests` или в `assignments`

2020-11-30 10:08 UTC, nikita111100 commented on etc/db/tables_online_testing.sql
> +  `test_id` INT NOT NULL,
Нет, не может, 1 вопрос к 1 тесту

2020-11-30 11:23 UTC, nikita111100 commented
Исправил замечания

2020-12-01 14:26 UTC, allikhachev commented on etc/db/tables_online_testing.sql
> +  `test_id` INT NOT NULL,
ну что ж, пусть будет так

2020-12-01 16:08 UTC, allikhachev requested changes

2020-12-01 16:08 UTC, allikhachev commented on etc/db/tables_online_testing.sql
> +  `correct_answer` INT NULL DEFAULT NULL,
кажется, здесь мы должны хранить `true` или `false`
используй `TINYINT(1)`

2020-12-01 16:08 UTC, allikhachev commented on etc/db/tables_online_testing.sql
> +)
удалить

2020-12-02 11:12 UTC, allikhachev approved these changes

2020-12-02 14:22 UTC, merged